# Generated by Django 5.1.6 on 2025-02-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="dob",
        ),
    ]
